#ifndef ACTION_HPP
#define ACTION_HPP

enum class Action {
    INTRODUCTION_START,
    ANIMATE_INTRODUCTION,
    INTRODUCTION_END,
    PICKING,
    MOVING,
    MATCHING_START,
    ANIMATE_MATCHING,
    MATCHING_END,
    FALLING_START,
    ANIMATE_FALLING,
    FALLING_END,
    COMPLETED
};

#endif // ACTION_HPP
