#ifndef BUTTONIMAGE_HPP
#define BUTTONIMAGE_HPP

enum class ButtonImage {
    KEYBOARD_MOVEMENT,
    KEYBOARD_CONFIRM,
    KEYBOARD_CANCEL,
    KEYBOARD_MENU,

    MOUSE_MOVEMENT,
    MOUSE_CONFIRM,
    MOUSE_CANCEL,
    MOUSE_MENU,

    GAMEPAD_MOVEMENT,
    GAMEPAD_CONFIRM,
    GAMEPAD_CANCEL,
    GAMEPAD_MENU,

    AMOUNT
};

#endif // BUTTONIMAGE_HPP
